### ISSUE TITLE
Support for Minimal Task Statuses

### ISSUE THREAD

**Issue by technotherion** [jaewonE/checkbox-styling-helper#3]
Minimal uses the following statuses: https://minimal.guide/checklists

Could an alternate scheme for Minimal be added? Your plugin is honestly super extensible so I do not mind doing so if you'd like me to.

**Comment by jaewonE** [comment]
Thank you for your interest. We appreciate your suggestion. We will look into adding an alternate scheme for Minimal and aim to have it implemented within a week after completing our current tasks.

**Comment by technotherion** [comment]
Great! Let me know if there is any way that I can help.

**Comment by technotherion** [comment]
Just verifying that the Minimal task statuses are working great. Thanks!

**Comment by jaewonE** [comment]
I was going to let you know after I finalized the charging function, but you already checked it! I'm glad it works well!
