### ISSUE TITLE
Unable to change checkbox of bullet that already contains text

### ISSUE THREAD

**Issue by technotherion** [jaewonE/checkbox-styling-helper#4]
### What does work
When creating a new bullet or checkbox without any other text on the line, hitting space and then typing `:` shows the popup box to choose a checkbox. 

### What doesn't work 
When a bullet point or checkbox already exists, adding a `:` anywhere in the line does not pop up the checkbox selection dialogue. 

I've tried after the checkbox and I've also tried the end of the line. 
![image](https://github.com/user-attachments/assets/9d7435de-135c-4596-9b2c-e1ee5a6085b4)
![image](https://github.com/user-attachments/assets/5eb24ee3-c770-4b04-88c0-7b6b184c146b)

### My workaround
Create a newline before the line I wish to change with a checkbox, type `:`, then hit `Del` to combine the two lines together.

**Comment by jaewonE** [comment]
The current code is designed to show the checkbox selection popup only when the `:` character is used on an empty line. However, I understand that there are situations where adding a checkbox to an existing line is necessary. To address this issue, we will implement support for a hotkey command, allowing users to add checkboxes even on lines with existing text.

**Comment by jaewonE** [comment]
In version 1.2.0, the following updates have been made:

1. Added five basic icons: number, unordered list, empty checkbox, half done, etc.
2. Provided a hot key to open the icon picker.(default: (Command + ;) on Mac / (Ctrl + ;) on Windows)
3. Enabled setting an icon via command even if there is already text on the current line.
4. Enabled changing an icon via command even if an icon is already set on the current line.
5. Allowed customization of the trigger.

Please update the plugin in the Obsidian Community Plugins: obsidian://show-plugin?id=checkbox-styling-helper

**Note!!**: If there is already content present, icon setting and changes can **only** be made via commands.
