### ISSUE TITLE
[FR] Add option to select checkbox when inside a callout

### ISSUE THREAD

**Issue by albertoloscerritos** [jaewonE/checkbox-styling-helper#8]
Hi. thanks for the awesome plugin.
I think one great addition would be the option to select which checkbox to use when inside a callout. Me, and also a lot of people depend a lot on callouts for their daily use of obsidian. At the moment I can select custom checkboxes to be inside of callouts:
![image](https://github.com/user-attachments/assets/3d7e010d-5f69-44e2-b978-f02da80b5674)

But I can't make the checkbox menu appear when I am inside the callout:
![checkbox_callout](https://github.com/user-attachments/assets/fe0af73e-028a-465d-b70e-93338bf601a1)

Thanks for your time :)

**Comment by jaewonE** [comment]
I didn't know that a simple plugin would get this much attention. I'll fix it once I'm done with what I'm doing now! Thanks :)

**Comment by albertoloscerritos** [comment]
What can I say 🤷‍♂️such a great plugin hahah 
thanks for the help and the awesome job

**Comment by jaewonE** [comment]
Hi!

Thanks for your patience. I'm happy to let you know that the Checkbox Styling Helper plugin now works within Callouts! Please update to version 1.3.0(obsidian://show-plugin?id=checkbox-styling-helper).

![test_result](https://github.com/user-attachments/assets/d7bdfdcf-da69-45fa-9507-4046ae926d75)

I've confirmed it works well on my side (using the Things theme). Could you check if it functions properly with your setup (Border theme)? If everything looks good, I'll go ahead and close this issue in about a week.

Thanks again for your support and interest!

**Comment by albertoloscerritos** [comment]
I can confirm it is working, I am using the AnuPpuccin theme btw.
Thanks for the update. Awesome plugin.
